import re
import os

def update_file(file_path, localizations):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    for key, values in localizations.items():
        # Find the block for the key
        pattern = re.compile(rf"'{key}': \{{(.*?)\}},", re.DOTALL)
        match = pattern.search(content)
        if match:
            original_block = match.group(1)
            new_block = original_block
            
            # Get UK description as source of truth - FIXED REGEX
            uk_match = re.search(r"'uk':\s+'((?:\\.|[^'])*)',", original_block)
            if not uk_match:
                print(f"Skipping {key}: No UK description found")
                continue
            
            for lang, text in values.items():
                if lang == 'uk': continue # Skip uk
                
                # Replace or add the language entry - handle escaped quotes in the replacement text
                safe_text = text.replace("'", "\\'")
                
                lang_pattern = re.compile(rf"'{lang}':\s+.*?,", re.DOTALL)
                if lang_pattern.search(new_block):
                    new_block = lang_pattern.sub(f"'{lang}':\n            '{safe_text}',", new_block)
                else:
                    new_block += f"\n        '{lang}':\n            '{safe_text}',"
            
            content = content.replace(original_block, new_block)
        else:
            print(f"Key {key} not found in file")

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)

# Final localizations for all remaining notes
# (Re-using the same data, but the script will now handle escaped quotes)
final_notes = {
    'wheel_note_smoky': {
        'en': 'Distinctive aroma of wood smoke or charcoal. Result of intense roasting or bean surface scorching. Classic in dark-roasted blends.',
        'de': 'Markantes Aroma von Holzrauch oder Holzkohle. Ergebnis intensiver Röstung oder Verbrennung der Bohnenoberfläche. Klassisch in dunklen Röstmischungen.',
        'fr': 'Arôme distinctif de fumée de bois ou de charbon de bois. Résultat d\'une torréfaction intense ou d\'un brûlage de la surface des grains. Classique dans les mélanges à torréfaction foncée.',
        'es': 'Aroma distintivo a humo de leña o carbón. Resultado de un tostado intenso o quemado superficial del grano. Clásico en mezclas de tostado oscuro.',
        'it': 'Aroma distintivo di fumo di legna o carbone. Risultato di una tostatura intensa o di una bruciatura superficiale del chicco. Classico nelle miscele a tostatura scura.',
        'pt': 'Aroma distinto de fumaça de madeira ou carvão. Resultado de torra intensa ou queima superficial do grão. Clássico em blends de torra escura.',
        'pl': 'Wyraźny aromat dymu drzewnego lub węgla drzewnego. Wynik intensywnego palenia lub przypalenia powierzchni ziarna. Klasyk w ciemno palonych mieszankach.',
        'nl': 'Kenmerkend aroma van houtrook of houtskool. Resultaat van intensief branden of verbranding van het boon-oppervlak. Klassiek in donkergebrande melanges.',
        'sv': 'Karaktäristisk arom av vedrök eller kol. Resultat av intensiv rostning eller bränning av bönans yta. Klassiskt i mörkrostade blandningar.',
        'tr': 'Odun dumanı veya odun kömürünün kendine özgü aroması. Yoğun kavurma veya çekirdek yüzeyinin yanmasının sonucudur. Koyu kavrulmuş karışımlarda klasiktir.',
        'ja': '木煙や炭の独特のアロマ。強火での焙煎や豆の表面の焦げの結果です。深煎りのブレンドでは定番の特徴です。',
        'ko': '장작 연기나 숯의 독특한 아로마입니다. 강한 로스팅이나 원두 표면이 그을린 결과입니다. 다크 로스팅 블렌드의 전형적인 특징입니다.',
        'zh': '木质烟熏或木炭的独特香气。是剧烈烘焙或豆表焦灼的结果。是深焙混合豆中的经典风味。',
        'ar': 'رائحة مميزة لدخان الخشب أو الفحم. ناتجة عن التحميص المكثف أو احتراق سطح الحبوب. كلاسيكية في خلطات التحميص الداكنة.',
    },
    'wheel_note_ashy': {
        'en': 'Dry, powdery scent of burnt wood or cold ash. Often indicates surface scorching during roast. Frequent in lower-quality dark roasts.',
        'de': 'Trockener, pudriger Duft von verbranntem Holz oder kalter Asche. Weist oft auf Oberflächenverbrennungen während der Röstung hin.',
        'fr': 'Odeur sèche et poudreuse de bois brûlé ou de cendre froide. Indique souvent un brûlage de surface pendant la torréfaction.',
        'es': 'Olor seco y polvoriento a madera quemada o ceniza fría. A menudo indica quemado superficial durante el tostado.',
        'it': 'Odore secco e polveroso di legno bruciato o cenere fredda. Spesso indica una bruciatura superficiale durante la tostatura.',
        'pt': 'Cheiro seco e polveroso de madeira queimada ou cinza fria. Frequentemente indica queima superficial durante a torra.',
        'pl': 'Suchy, pudrowy zapach spalonego drewna lub zimnego popiołu. Często wskazuje na przypalenie powierzchni podczas palenia.',
        'nl': 'Droge, poederachtige geur van verbrand hout of koude as. Wijst vaak op oppervlakteverbranding tijdens het branden.',
        'sv': 'Torr, pudrig doft av bränt trä oder kall aska. Tyder ofta på ytlig bränning under rostningen.',
        'tr': 'Yanmış odun veya soğuk külün kuru, tozlu kokusu. Genellikle kavurma sırasında yüzeyin yanmasını gösterir.',
        'ja': '焼けた木や冷えた灰のような、乾燥した粉っぽい香り。焙煎中の表面の焦げを示していることが多いです。',
        'ko': '탄 나무나 찬 재의 건조하고 가루 같은 향입니다. 로스팅 중 표면이 그을렸음을 나타내는 경우가 많습니다.',
        'zh': '烧焦的木头或冷灰的干燥粉末味。通常预示着烘焙过程中的表面焦灼。',
        'ar': 'رائحة جافة وترابية للخشب المحترق أو الرماد البارد. غالباً ما تشير إلى احتراق السطح أثناء التحميص.',
    },
    'wheel_note_olive_oil': {
        'en': 'Heavy, viscous and slightly fatty mouthfeel. Derived from concentrated lipid content. Signature of specific high-altitude Ethiopian lots.',
        'de': 'Schweres, viskoses und leicht fettiges Mundgefühl. Abgeleitet von konzentriertem Lipidgehalt. Kennzeichen spezifischer äthiopischer Hochlandlots.',
        'fr': 'Sensation en bouche lourde, visqueuse et légèrement grasse. Dérivé d\'une teneur concentrée en lipides. Signature de lots éthiopiens d\'altitude spécifiques.',
        'es': 'Sensación en boca pesada, viscosa y ligeramente grasa. Derivada del contenido concentrado de lípidos. Firma de lotes etíopes específicos de gran altitud.',
        'it': 'Sensazione in bocca pesante, viscosa e leggermente grassa. Deriva dal contenuto lipidico concentrato. Caratteristica di specifici lotti etiopi d\'alta quota.',
        'pt': 'Sensação na boca pesada, viscosa e ligeiramente gordurosa. Derivada do conteúdo lipídico concentrado. Assinatura de lotes etíopes de alta altitude específicos.',
        'pl': 'Ciężkie, lepkie i nieco tłuste odczucie w ustach. Pochodzi ze skoncentrowanej zawartości lipidów. Wizytówka specyficznych etiopskich partii kawy.',
        'nl': 'Zwaar, stroperig en licht vet mondgevoel. Afgeleid van geconcentreerd lipidengehalte. Kenmerkend voor specifieke Ethiopische hoogland-kavels.',
        'sv': 'Tung, viskös och något fettig munkänsla. Kommer från koncentrerat lipidinnehåll. Signatur för specifika etiopiska höghöjdspartier.',
        'tr': 'Ağır, yapışkan ve hafif yağlı ağız hissi. Konsantre lipid içeriğinden türetilmiştir. Belirli yüksek rakımlı Etiyopya lotlarının imzasıdır.',
        'ja': '重く、粘り気があり、わずかに脂っこい口当たり。濃縮された脂質含有量に由来します。特定のエチオピア高地産の豆の特徴です。',
        'ko': '무겁고 끈적하며 약간 기름진 마우스필입니다. 농축된 지질 함량에서 유래합니다. 특정 고산지대 에티오피아 커피의 특징입니다.',
        'zh': '重厚、粘稠且略带油腻的口感。源于浓缩的脂质含量。是特定高海拔埃塞俄比亚批次的特征。',
        'ar': 'قوام ثقيل ولزج ودهني قليلاً. مشتق من محتوى الدهون المركز. علامة مميزة لمحاصيل إثيوبية معينة عالية الارتفاع.',
    },
    'wheel_note_raw': {
        'en': 'Aggressive green and undeveloped bean flavors. Result of significantly under-roasted lots. Often accompanied by astringency.',
        'de': 'Aggressive grüne und unentwickelte Bohnenaromen. Ergebnis deutlich zu kurz gerösteter Chargen. Oft begleitet von Adstringenz.',
        'fr': 'Arômes verts agressifs et grains non développés. Résultat de lots nettement sous-torréfiés. Souvent accompagné d\'astringence.',
        'es': 'Sabores verdes agresivos y de grano no desarrollado. Resultado de lotes significativamente poco tostados. A menudo acompañados de astringencia.',
        'it': 'Sapori verdi aggressivi e chicchi non sviluppati. Risultato di lotti significativamente sotto-tostati. Spesso accompagnati da astringenza.',
        'pt': 'Sabores verdes agressivos e grãos não desenvolvidos. Resultado de lotes significativamente sub-torrados. Frequentemente acompanhados de adstringência.',
        'pl': 'Agresywne zielone i nierozwinięte smaki ziarna. Wynik znacznie niedopalonych partii kawy. Często towarzyszy im cierpkość.',
        'nl': 'Agressieve groene en onontwikkelde boonaroma\'s. Resultaat van aanzienlijk te licht gebrande kavels. Vaak vergezeld van wrangheid.',
        'sv': 'Aggressiva gröna och outvecklade bönaromer. Resultat av betydligt underrostade partier. Åtföljs ofta av strävhet.',
        'tr': 'Agresif yeşil ve gelişmemiş çekirdek tatları. Önemli ölçüde az kavrulmuş lotların sonucudur. Genellikle burukluk eşlik eder.',
        'ja': '刺激的な緑っぽさと、未発達な豆のフレーバー。焙煎不足の豆によく見られます。多くの場合、渋みを伴います。',
        'ko': '자극적인 풀향과 발현되지 않은 원두의 풍미입니다. 로스팅이 상당히 부족한 결과입니다. 종종 떫은 맛을 동반합니다.',
        'zh': '强烈的青涩味和未完全烘焙成熟的豆味。是烘焙严重不足的结果。通常伴有涩感。',
        'ar': 'نكهات خضراء حادة وغير ناضجة للحبوب. ناتجة عن تحميص غير مكتمل بشكل كبير. غالباً ما يصاحبها طعم قابض.',
    },
    'wheel_note_under_ripe': {
        'en': 'Sharp, vegetal notes like raw seeds. Indicates harvest of immature coffee cherries. Indicator of inconsistent farming practices.',
        'de': 'Scharfe, pflanzliche Noten wie rohe Samen. Weist auf die Ernte unreifer Kaffeekirschen hin. Indikator für inkonsistente Anbaupraktiken.',
        'fr': 'Notes végétales vives comme des graines crues. Indique la récolte de cerises de café immatures. Indicateur de pratiques agricoles incohérentes.',
        'es': 'Notas vegetales punzantes como semillas crudas. Indica la cosecha de cerezas de café inmaduras. Indicador de prácticas agrícolas inconsistentes.',
        'it': 'Note vegetali pungenti come semi crudi. Indica la raccolta di ciliegie di caffè immature. Indicatore di pratiche agricole incoerenti.',
        'pt': 'Notas vegetais pungentes como sementes cruas. Indica a colheita de cerejas de café imaturas. Indicador de práticas agrícolas inconsistentes.',
        'pl': 'Ostre, roślinne nuty przypominające surowe nasiona. Wskazują na zbiór niedojrzałych wisienek kawy. Indikator niespójnych praktyk rolniczych.',
        'nl': 'Scherpe, plantaardige tonen zoals rauwe zaden. Wijst op de oogst van onrijpe koffiebessen. Indicatie voor inconsistente landbouwpraktijken.',
        'sv': 'Skarpa, vegetabiliska noter som råa frön. Tyder på skörd av omogna kaffebär. Indikator på inkonsekventa jordbruksmetoder.',
        'tr': 'Çiğ tohumlar gibi keskin, bitkisel notalar. Olgunlaşmamış kahve meyvelerinin toplandığını gösterir. Tutarsız tarım uygulamalarının bir göstergesidir.',
        'ja': '生の種子のような、鋭い植物系のノート。未熟なコーヒーチェリーの収穫を示しています。一貫性のない栽培方法の指標です。',
        'ko': '생 씨앗 같은 자극적인 식물성 노트입니다. 덜 익은 커피 체리를 수확했음을 나타냅니다. 일관되지 않은 농업 관행의 지표입니다.',
        'zh': '尖锐的、像生种子般的植物味。预示着采摘了未成熟的咖啡樱桃。是不规范农事操作的指标。',
        'ar': 'نوتات نباتية حادة مثل البذور الخام. تشير إلى حصاد كرز القهوة غير الناضج. مؤشر على ممارسات زراعية غير متسقة.',
    },
    'wheel_note_peapod': {
        'en': 'Starch-like, green bean aroma. Associated with specific chemical compounds in underdeveloped roasts. Found in quick-dried lots.',
        'de': 'Stärkeähnliches, grünes Bohnenaroma. Verbunden mit spezifischen chemischen Verbindungen in unterentwickelten Röstungen.',
        'fr': 'Arôme de haricot vert, proche de l\'amidon. Associé à des composés chimiques spécifiques dans les torréfactions sous-développées.',
        'es': 'Aroma a judía verde, similar al almidón. Asociado con compuestos químicos específicos en tostados poco desarrollados.',
        'it': 'Aroma di fagiolino, simile all\'amido. Associato a specifici composti chimici nelle tostature poco sviluppate.',
        'pt': 'Aroma de vagem, semelhante ao amido. Associado a compostos químicos específicos em torras subdesenvolvidas.',
        'pl': 'Skrobiowy aromat zielonej fasoli. Związany ze specyficznymi związkami chemicznymi в niedostatecznie rozwiniętych paleniach.',
        'nl': 'Zetmeelachtig, sperzieboonaroma. Geassocieerd met specifieke chemische verbindingen in onvoldoende ontwikkelde brandingen.',
        'sv': 'Stärkelseliknande doft av gröna bönor. Förknippas med specifika kemiska föreningar i outvecklade rostningar.',
        'tr': 'Nişasta benzeri, taze fasulye aroması. Az gelişmiş kavurmalardaki özel kimyasal bileşiklerle ilişkilidir.',
        'ja': 'デンプンのような、青豆のアロマ。焙煎不足の豆に含まれる特定の化学物質に関連しています。',
        'ko': '전분 같은 풋콩의 아로마입니다. 충분히 로스팅되지 않은 원두의 특정 화학 화합물과 관련이 있습니다.',
        'zh': '像淀粉般的青豆香气。与烘焙不足中的特定化学成分有关。',
        'ar': 'رائحة الفاصوليا الخضراء التي تشبه النشا. مرتبطة بمركبات كيميائية معينة في التحميص غير المكتمل.',
    },
    'wheel_note_fresh': {
        'en': 'Bright, lively and slightly grassy notes. Characteristic of newly harvested and processed lots. Hallmark of seasonal freshness.',
        'de': 'Helle, lebendige und leicht grasige Noten. Charakteristisch für frisch geerntete und verarbeitete Partien.',
        'fr': 'Notes vives, animées et légèrement herbacées. Caractéristique des lots fraîchement récoltés et traités.',
        'es': 'Notas brillantes, vivas y ligeramente herbáceas. Característico de lotes recién cosechados y procesados.',
        'it': 'Note brillanti, vivaci e leggermente erbacee. Caratteristico dei lotti appena raccolti e lavorati.',
        'pt': 'Notas brilhantes, vivas e ligeiramente herbáceas. Caratterístico de lotes recém-colhidos e processados.',
        'pl': 'Wyraźne, żywe i nieco trawiaste nuty. Charakterystyczne для świeżo zebranych i przetworzonych partii kawy.',
        'nl': 'Heldere, levendige en licht grasachtige tonen. Kenmerkend voor pas geoogste en verwerkte kavels.',
        'sv': 'Ljusa, livliga och något gräsiga noter. Karaktäristiskt för nyskördade och bearbetade partier.',
        'tr': 'Parlak, canlı ve hafif otsu notalar. Yeni hasat edilmiş ve işlenmiş lotların özelliğidir.',
        'ja': '明るく、生き生きとした、わずかに草のようなノート。収穫・精製したての豆の特徴です。',
        'ko': '밝고 활기차며 약간의 풀향이 나는 노트입니다. 갓 수확하고 가공한 커피의 특징입니다.',
        'zh': '明亮、活泼且略带青草气息的风味。是新近收获和处理批次的特征。',
        'ar': 'نوتات ساطعة وحيوية وعشبية قليلاً. مميزة للمحاصيل التي تم حصادها ومعالجتها حديثاً.',
    },
    'wheel_note_vegetative': {
        'en': 'Broad herbal profile encompassing leaves and stems. Reflects high levels of specific pyrazines. Characteristic of Indonesian Mandheling.',
        'de': 'Breites Kräuterprofil, das Blätter und Stängel umfasst. Spiegelt hohe Werte spezifischer Pyrazine wider.',
        'fr': 'Profil herbacé large englobant les feuilles et les tiges. Reflète des niveaux élevés de pyrazines spécifiques.',
        'es': 'Perfil herbal amplio que abarca hojas y tallos. Refleja altos niveles de pirazinas específicas.',
        'it': 'Ampio profilo erbaceo che comprende foglie e steli. Riflette alti livelli di pirazine specifiche.',
        'pt': 'Amplo perfil herbáceo que abrange folhas e caules. Reflete altos níveis de pirazinas específicas.',
        'pl': 'Szeroki profil ziołowy obejmujący liście i łodygi. Odzwierciedla wysoki poziom specyficznych pirazyn.',
        'nl': 'Breed kruidenprofiel met bladeren en stengels. Weerspiegelt hoge gehalten aan specifieke pyrazinen.',
        'sv': 'Bred örtprofil som omfattar blad och stjälkar. Speglar höga nivåer av specifika pyraziner.',
        'tr': 'Yaprakları ve gövdeleri kapsayan geniş otsu profil. Özel pirazinlerin yüksek seviyelerini yansıtır.',
        'ja': '葉や茎を含む幅広いハーブのプロファイル。特定のピラジンの高含有量を反映しています。',
        'ko': '잎과 줄기를 아우르는 광범위한 허브 프로파일입니다. 특정 피라진의 높은 함량을 반영합니다.',
        'zh': '包含叶片和茎部的广泛草本风味。反映了高含量的特定吡嗪。',
        'ar': 'ملف عشبي واسع يشمل الأوراق والسيقان. يعكس مستويات عالية من بيرازينات معينة.',
    },
    'wheel_note_hay_like': {
        'en': 'Dry, sweet grass and straw profile. Often indicates early signs of bean aging or specific terroir dryness. Frequent in processed Brazilian lots.',
        'de': 'Trockener, süßer Gras- und Strohgeschmack. Weist oft auf erste Anzeichen von Bohnenalterung oder spezifische Terroir-Trockenheit hin.',
        'fr': 'Profil d\'herbe sèche et sucrée et de paille. Indique souvent les premiers signes de vieillissement des grains ou une sécheresse spécifique du terroir.',
        'es': 'Perfil de hierba seca y dulce y paja. A menudo indica signos tempranos de envejecimiento del grano o sequedad específica del terroir.',
        'it': 'Profilo di erba secca e dolce e paglia. Spesso indica i primi segni di invecchiamento del chicco o una specifica aridità del terroir.',
        'pt': 'Perfil de grama seca e doce e palha. Frequentemente indica sinais iniciais de envelhecimento do grão ou secura específica do terroir.',
        'pl': 'Profil suchej, słodkiej trawy i słomy. Często wskazuje na wczesne oznaki starzenia się ziaren lub specyficzną suchość terroir.',
        'nl': 'Droog, zoet gras- en stroprofiel. Wijst vaak op vroege tekenen van boonveroudering of specifieke terroir-droogte.',
        'sv': 'Profil av torrt, sött gräs och halm. Tyder ofta på tidiga tecken på bönåldring eller specifik terroir-torrhet.',
        'tr': 'Kuru, tatlı ot ve saman profili. Genellikle çekirdek yaşlanmasının erken belirtilerini veya özel teruar kuruluğunu gösterir.',
        'ja': '乾燥した、甘い草やわらのようなプロファイル。豆の老化の兆候や、特定の産地の乾燥を示していることが多いです。',
        'ko': '건조하고 달콤한 풀과 짚의 프로파일입니다. 원두의 노화 초기 징후나 특정 테루아의 건조함을 나타내는 경우가 많습니다.',
        'zh': '干燥、甜草和稻草的风味。通常预示着咖啡豆陈化的早期迹象或特定的地域干燥度.',
        'ar': 'نكهة العشب الجاف والحلو والقش. غالباً ما تشير إلى علامات مبكرة لتقادم الحبوب أو جفاف تربة معين.',
    },
    'wheel_note_herb_like': {
        'en': 'Savory herb notes like rosemary or thyme. Correlated with specific volcanic soil profiles. Hallmark of specialty lots from Timor and Bali.',
        'de': 'Herzhafte Kräuternoten wie Rosmarin oder Thymian. Korreliert mit spezifischen vulkanischen Bodenprofilen.',
        'fr': 'Notes d\'herbes savoureuses comme le romarin ou le thym. Corrélé à des profils de sols volcaniques spécifiques.',
        'es': 'Notas de hierbas sabrosas como el romero o el tomillo. Correlacionado con perfiles específicos de suelo volcánico.',
        'it': 'Note di erbe aromatiche come rosmarino o timo. Correlato a specifici profili di suolo vulcanico.',
        'pt': 'Notas de ervas salgadas como alecrim ou tomilho. Correlacionado com perfis específicos de solo vulcânico.',
        'pl': 'Wytrawne nuty ziół, takich jak rozmaryn lub tymianek. Skorelowane ze specyficznymi wulkanicznymi profilami glebowymi.',
        'nl': 'Hartige kruidentonen zoals rozemarijn of tijm. Gecorreleerd met specifieke vulkanische bodemprofielen.',
        'sv': 'Smakrika örtnoter som rosmarin eller timjan. Korrelerat med specifika vulkaniska jordprofiler.',
        'tr': 'Biberiye veya kekik gibi iştah açıcı otsu notalar. Özel volkanik toprak profilleri ile ilişkilidir.',
        'ja': 'ローズマリーやタイムのような風味豊かなハーブのノート。特定の火山性土壌と相関しています。',
        'ko': '로즈마리나 타임 같은 짭짤한 허브 노트입니다. 특정 화산 토양 프로파일과 상관관계가 있습니다.',
        'zh': '咸鲜的香草味，如迷延香或百里香。与特定的火山土壤成分有关。',
        'ar': 'نوتات عشبية مالحة مثل إكليل الجبل أو الزعتر. مرتبطة بملفات تربة بركانية معينة.',
    },
    'wheel_note_sour_aromatics': {
        'en': 'Tangy and complex acidic scents. Essential for structure in high-grown coffees. Present in almost all high-attribute Central Americans.',
        'de': 'Spritzige und komplexe säuerliche Düfte. Essentiell für die Struktur in Hochlandkaffees.',
        'fr': 'Parfums acidulés et complexes. Essentiel pour la structure des cafés d\'altitude.',
        'es': 'Aromas ácidos intensos y complejos. Esencial para la estructura en cafés de altura.',
        'it': 'Profumi acidi pungenti e complessi. Essenziale per la struttura nei caffè d\'alta quota.',
        'pt': 'Aromas ácidos intensos e complexos. Essencial para a estrutura em cafés de altitude.',
        'pl': 'Cierpkie i złożone kwaśne zapachy. Niezbędne dla struktury kaw wysokogórskich.',
        'nl': 'Pittige en complexe zure geuren. Essentieel voor de structuur in hooggelegen koffiesoorten.',
        'sv': 'Syrliga och komplexa dofter. Viktigt för strukturen i höghöjdskaffe.',
        'tr': 'Keskin ve karmaşık asidik kokular. Yüksek rakımlı kahvelerde yapı için gereklidir.',
        'ja': '酸味のある、複雑で刺激的な香り。高地産のコーヒーの構造には不可欠な要素です。',
        'ko': '톡 쏘고 복합적인 산미의 향입니다. 고산지대 커피의 구조감에 필수적입니다.',
        'zh': '强烈且复杂的酸香。对于高海拔咖啡的结构至关重要。',
        'ar': 'روائح حامضية نفاذة ومعقدة. أساسية لقوام القهوة المزروعة على ارتفاعات عالية.',
    },
    'wheel_note_acetic_acid': {
        'en': 'Sharp, vinegar-like acidity. Normal at low levels; indicates over-fermentation if aggressive. Found in long-fermented "Funky" Colombian lots.',
        'de': 'Scharfe, essigartige Säure. Bei niedrigen Werten normal; weist auf Überfermentation hin, wenn sie aggressiv ist.',
        'fr': 'Acidité vive, proche du vinaigre. Normale à faible dose ; indique une sur-fermentation si elle est agressive.',
        'es': 'Acidez punzante, similar al vinagre. Normal a niveles bajos; indica sobrefermentación si es agresiva.',
        'it': 'Acidità pungente, simile all\'aceto. Normale a bassi livelli; indica sovrafermentazione se aggressiva.',
        'pt': 'Acidez pungente, semelhante ao vinagre. Normal em níveis baixos; indica superfermentação se agressiva.',
        'pl': 'Ostra, octowa kwasowość. Normalna na niskich poziomach; wskazuje na nadmierną fermentację, jeśli jest agresywna.',
        'nl': 'Scherpe, azijnachtige zuurgraad. Normaal op lage niveaus; wijst op overfermentatie als het agressief is.',
        'sv': 'Skarp, vinägerliknande syra. Normal vid låga nivåer; tyder på överfermentering om den är aggressiv.',
        'tr': 'Keskin, sirke benzeri asidite. Düşük seviyelerde normaldir; agresif ise aşırı fermantasyonu gösterir.',
        'ja': 'ツンとする、酢のような酸味。少量なら正常ですが、強い場合は過発酵を示しています。',
        'ko': '시큼한 식초 같은 산미입니다. 낮은 농도에서는 정상이지만, 강할 경우 과발효를 나타냅니다.',
        'zh': '尖锐、像醋般的酸度。低含量时正常；如果非常强烈则预示着发酵过度。',
        'ar': 'حموضة حادة تشبه الخل. طبيعية بمستويات منخفضة؛ تشير إلى فرط التخمر إذا كانت حادة.',
    },
    'wheel_note_butyric_acid': {
        'en': 'Heady and pungent acid profile reminiscent of Greek yogurt or cheese. Result of intensive metabolic processing. Signature of modern experimental ferments.',
        'de': 'Berauschendes und stechendes Säureprofil, das an griechischen Joghurt oder Käse erinnert.',
        'fr': 'Profil acide entêtant et piquant rappelant le yaourt grec ou le fromage.',
        'es': 'Perfil ácido intenso y penetrante que recuerda al yogur griego o al queso.',
        'it': 'Profilo acido inebriante e pungente che ricorda lo yogurt greco o il formaggio.',
        'pt': 'Perfil ácido inebriante e pungente que lembra iogurte grego ou queijo.',
        'pl': 'Uderzający i ostry profil kwasowy przypominający grecki jogurt lub ser.',
        'nl': 'Bedwelmend en doordringend zuurprofiel dat doet denken aan Griekse yoghurt of kaas.',
        'sv': 'Berusande och stickande syraprofil som påminner om grekisk yoghurt eller ost.',
        'tr': 'Yunan yoğurdu veya peyniri andıran baş döndürücü ve keskin asit profili.',
        'ja': 'ギリシャヨーグルトやチーズを思わせる、刺激的でツンとした酸味のプロファイル。',
        'ko': '그릭 요거트나 치즈를 연상시키는 자극적이고 톡 쏘는 산미 프로파일입니다.',
        'zh': '令人眩晕且刺激的酸感，让人联想起希腊酸奶或奶酪。',
        'ar': 'ملف حامضي قوي ونفاذ يشبه الزبادي اليوناني أو الجبن.',
    },
    'wheel_note_isovaleric_acid': {
        'en': 'Strong, cheese-like or sweaty acid note. Characteristic of extremely long anaerobic fermentations. Often polarizing but sought after in modern competitions.',
        'de': 'Starke, käseartige oder schweißige Säurenote. Charakteristisch für extrem lange anaerobe Fermentationen.',
        'fr': 'Note acide forte, proche du fromage ou de la transpiration. Caractéristique des fermentations anaérobies extrêmement longues.',
        'es': 'Nota ácida fuerte, similar al queso o al sudor. Característico de fermentaciones anaeróbicas extremadamente largas.',
        'it': 'Nota acida forte, simile al formaggio o al sudore. Caratteristico di fermentazioni anaerobiche estremamente lunghe.',
        'pt': 'Nota ácida forte, semelhante a queijo ou suor. Característica de fermentações anaeróbicas extremamente longas.',
        'pl': 'Silna, serowa lub potna nuta kwasowa. Charakterystyczna dla niezwykle długich fermentacji beztlenowych.',
        'nl': 'Sterke, kaasachtige of zweeterige zuurnoot. Kenmerkend voor extreem lange anaerobe fermentaties.',
        'sv': 'Stark, ostliknande eller svettig syranot. Karaktäristiskt för extremt långa anaeroba fermenteringar.',
        'tr': 'Güçlü, peynirimsi veya terli asit notası. Son derece uzun anaerobik fermantasyonların özelliğidir.',
        'ja': 'チーズや汗のような強い酸味。非常に長い嫌気性発酵（アナエロビック）の特徴です。',
        'ko': '강한 치즈 향이나 땀 냄새 같은 산미입니다. 매우 긴 무산소 발효의 특징입니다.',
        'zh': '强烈的奶酪味或汗臭酸味。是极长时间厌氧发酵的特征。',
        'ar': 'نوتة حامضية قوية تشبه الجبن أو العرق. مميزة للتخمر اللاهوائي الطويل جداً.',
    },
    'wheel_note_citric_acid': {
        'en': 'Pure, refreshing and bright acidity. The primary acid in most specialty coffees. Quintessential Kenyan and Colombian profile.',
        'de': 'Reine, erfrischende und helle Säure. Die primäre Säure in den meisten Spezialitätenkaffees.',
        'fr': 'Acidité pure, rafraîchissante et vive. L\'acide principal dans la plupart des cafés de spécialité.',
        'es': 'Acidez pura, refrescante y brillante. El ácido principal en la mayoría de los cafés de especialidad.',
        'it': 'Acidità pura, rinfrescante e brillante. L\'acido primario nella maggior parte dei caffè specialty.',
        'pt': 'Acidez pura, refrescante e brilhante. O ácido primário na maioria dos cafés de especialidade.',
        'pl': 'Czysta, odświeżająca i jasna kwasowość. Główny kwas w większości kaw specialty.',
        'nl': 'Pure, verfrissende en heldere zuurgraad. Het belangrijkste zuur in de meeste specialty koffies.',
        'sv': 'Ren, uppfriskande och ljus syra. Den främsta syran i de flesta specialkaffen.',
        'tr': 'Saf, ferahlatıcı ve parlak asidite. Çoğu nitelikli kahvedeki birincil asittir.',
        'ja': '純粋で爽やか、そして明るい酸味。ほとんどのスペシャルティコーヒーに含まれる主要な酸です。',
        'ko': '순수하고 상쾌하며 밝은 산미입니다. 대부분의 스페셜티 커피에서 발견되는 주요 산미입니다.',
        'zh': '纯净、清爽且明亮的酸度。是大多数精品咖啡中的主要酸类。',
        'ar': 'حموضة نقية ومنعشة وساطعة. الحمض الأساسي في معظم أنواع القهوة المختصة.',
    },
    'wheel_note_malic_acid': {
        'en': 'Crisp and structural acidity that provides body and sweetness. Common in heavy coffee varieties like Bourbon. Hallmarks of Burundian coffees.',
        'de': 'Knackige und strukturelle Säure, die Körper und Süße verleiht. Häufig bei schweren Kaffeesorten wie Bourbon.',
        'fr': 'Acidité croquante et structurelle qui apporte corps et douceur. Commune dans les variétés de café lourdes comme le Bourbon.',
        'es': 'Acidez crujiente y estructural que aporta cuerpo y dulzor. Común en variedades de café pesadas como Bourbon.',
        'it': 'Acidità croccante e strutturale che conferisce corpo e dolcezza. Comune nelle varietà di caffè pesanti come il Bourbon.',
        'pt': 'Acidez crocante e estrutural que proporciona corpo e doçura. Comum em variedades de café pesadas como Bourbon.',
        'pl': 'Chrupka i strukturalna kwasowość, która zapewnia body i słodycz. Powszechna w ciężkich odmianach kawy, takich як Bourbon.',
        'nl': 'Frisse en structurele zuurgraad die body en zoetheid geeft. Veelvoorkomend in zware koffiesoorten zoals Bourbon.',
        'sv': 'Frisk och strukturell syra som ger fyllighet och sötma. Vanligt i tunga kaffesorter som Bourbon.',
        'tr': 'Gövde ve tatlılık sağlayan gevrek ve yapısal asidite. Bourbon gibi ağır kahve çeşitlerinde yaygındır.',
        'ja': 'ボディと甘みを与える、歯切れの良い構造的な酸味。ブルボンのような重厚な品種に多く見られます。',
        'ko': '바디감과 단맛을 제공하는 아삭하고 구조적인 산미입니다. 버번과 같은 무거운 커피 품종에서 흔합니다.',
        'zh': '爽脆且有结构感的酸度，能提供醇厚度和甜感。在波旁等重厚品种中很常见。',
        'ar': 'حموضة مقرمشة وهيكلية توفر القوام والحلاوة. شائعة في أصناف القهوة الثقيلة مثل بوربون.',
    },
    'wheel_note_winey': {
        'en': 'Heady, fruity acidity reminiscent of red wine. Result of controlled fruit fermentation. Iconic for natural Ethiopians and Colombian anaerobic lots.',
        'de': 'Berauschende, fruchtige Säure, die an Rotwein erinnert. Ergebnis einer kontrollierten Fruchtfermentation.',
        'fr': 'Acidité fruitée et entêtante rappelant le vin rouge. Résultat d\'une fermentation contrôlée des fruits.',
        'es': 'Acidez frutal e intensa que recuerda al vino tinto. Resultado de la fermentación controlada de la fruta.',
        'it': 'Acidità fruttata e inebriante che ricorda il vino rosso. Risultato di una fermentazione controllata della frutta.',
        'pt': 'Acidez frutada e inebriante que lembra vinho tinto. Resultado da fermentação controlada da fruta.',
        'pl': 'Uderzająca, owocowa kwasowość przypominająca czerwone wino. Wynik kontrolowanej fermentacji owoców.',
        'nl': 'Bedwelmende, fruitige zuurgraad die doet denken aan rode wijn. Resultaat van gecontroleerde fruitfermentatie.',
        'sv': 'Berusande, fruktig syra som påminner om rött vin. Resultat av kontrollerad fruktfermentering.',
        'tr': 'Kırmızı şarabı andıran baş döndürücü, meyvemsi asidite. Kontrollü meyve fermantasyonunun sonucudur.',
        'ja': '赤ワインを思わせる、芳醇でフルーティーな酸味。管理された果実発酵の結果です。',
        'ko': '레드 와인을 연상시키는 풍부하고 과일 같은 산미입니다. 잘 조절된 과일 발효의 결과입니다.',
        'zh': '让人联想起红酒的醇厚果酸。是经过人工控制的果实发酵结果。',
        'ar': 'حموضة فاكهية قوية تشبه النبيذ الأحمر. ناتجة عن تخمر فاكهة محكم.',
    },
    'wheel_note_whiskey': {
        'en': 'Complex, alcoholic and woody notes. Indicates intense, prolonged fermentation. Typical of experimental "Spirit-process" lots.',
        'de': 'Komplexe, alkoholische und holzige Noten. Weist auf intensive, längere Fermentation hin.',
        'fr': 'Notes complexes, alcoolisées et boisées. Indique une fermentation intense et prolongée.',
        'es': 'Notas complexes, alcohólicas y amaderadas. Indica una fermentación intensa y prolongada.',
        'it': 'Note complesse, alcoliche e legnose. Indica una fermentazione intensa e prolungata.',
        'pt': 'Notas complexas, alcoólicas e amadeiradas. Indica fermentação intensa e prolongada.',
        'pl': 'Złożone, alkoholowe i drzewne nuty. Wskazują na intensywną, przedłużoną fermentację.',
        'nl': 'Complex, alcoholisch en houtachtig. Wijst op intensieve, langdurige fermentatie.',
        'sv': 'Komplexa, alkoholhaltiga och träiga noter. Tyder på intensiv, långvarig fermentering.',
        'tr': 'Karmaşık, alkollü ve odunsu notalar. Yoğun, uzun süreli fermantasyonu gösterir.',
        'ja': '複雑でアルコール感のある、ウッディなノート。強烈で長期間の発酵を示しています。',
        'ko': '복합적이고 알코올 느낌이 나는 우디한 노트입니다. 강렬하고 장기간의 발효를 나타냅니다.',
        'zh': '复杂、酒精味和木质风味。预示着剧烈且长时间的发酵。',
        'ar': 'نوتات معقدة وكحولية وخشبية. تشير إلى تخمر مكثف وطويل.',
    },
    'wheel_note_over_ripe': {
        'en': 'Deep, slightly boozy sweetness of fruit just past its prime. Adds weight to natural processed lots. Common in Brazilian naturals.',
        'de': 'Tiefe, leicht alkoholische Süße von Früchten, die ihren Höhepunkt überschritten haben.',
        'fr': 'Douceur profonde, légèrement alcoolisée, de fruits juste après leur apogée.',
        'es': 'Dulzura profunda, ligeramente alcohólica, de fruta que acaba de pasar su mejor momento.',
        'it': 'Dolcezza profonda, leggermente alcolica, di frutta appena passata il momento migliore.',
        'pt': 'Doçura profunda, ligeiramente alcoólica, de fruta que acabou de passar do seu auge.',
        'pl': 'Głęboka, nieco alkoholowa słodycz owoców, które właśnie minęły szczyt dojrzałości.',
        'nl': 'Diepe, licht alcoholische zoetheid van fruit dat net over zijn hoogtepunt heen is.',
        'sv': 'Djup, något alkoholhaltig sötma från frukt som precis passerat sin höjdpunkt.',
        'tr': 'Zirvesini henüz geçmiş meyvelerin derin, hafif içkimsi tatlılığı.',
        'ja': '全盛期を過ぎたばかり의 果実の、深く、わずかに酒のような甘み。',
        'ko': '절정기를 막 지난 과일의 깊고 약간 술 같은 단맛입니다.',
        'zh': '过熟果实那种深厚且略带酒味的甜感。',
        'ar': 'حلاوة عميقة وفاكهية قليلاً لثمار تجاوزت ذروة نضجها.',
    },
    'wheel_note_rubber': {
        'en': 'Dense, pungent note often associated with the genetics of Robusta. Can appear in some intense Brazilian clones. Rare in Arabica.',
        'de': 'Dichte, stechende Note, die oft mit der Genetik von Robusta in Verbindung gebracht wird.',
        'fr': 'Note dense et piquante souvent associée à la génétique du Robusta.',
        'es': 'Nota densa y penetrante a menudo asociada con la genética de Robusta.',
        'it': 'Nota densa e pungente spesso associata alla genetica della Robusta.',
        'pt': 'Nota densa e pungente frequentemente associada à genética do Robusta.',
        'pl': 'Gęsta, ostra nuta często kojarzona z genetyką Robusty.',
        'nl': 'Dichte, doordringende noot die vaak wordt geassocieerd met de genetica van Robusta.',
        'sv': 'Tät, stickande not som ofta förknippas med Robustas genetik.',
        'tr': 'Genellikle Robusta genetiği ile ilişkilendirilen yoğun, keskin nota.',
        'ja': 'ロブスタ種の遺伝学に関連することが多い、密度が高く刺激的なノート。',
        'ko': '종종 로부스타 품종의 유전적 특성과 관련된 밀도 높고 자극적인 노트입니다.',
        'zh': '通常与罗布斯塔基因相关的浓烈刺激味。',
        'ar': 'نوتة كثيفة ونفاذة ترتبط غالباً بجينات روبوستا.',
    },
    'wheel_note_petroleum': {
        'en': 'Sharp, industrial aromatic note. Usually indicates contamination or major storage faults. Unacceptable in specialty coffee.',
        'de': 'Scharfe, industrielle aromatische Note. Weist normalerweise auf Verunreinigungen oder schwere Lagerfehler hin.',
        'fr': 'Note aromatique industrielle et vive. Indique généralement une contamination ou des défauts de stockage majeurs.',
        'es': 'Nota aromática industrial punzante. Por lo general, indica contaminación o fallas importantes de almacenamiento.',
        'it': 'Nota aromatica industriale pungente. Di solito indica contaminazione o gravi difetti di conservazione.',
        'pt': 'Nota aromática industrial pungente. Geralmente indica contaminação ou grandes falhas de armazenamento.',
        'pl': 'Ostra, przemysłowa nuta aromatyczna. Zazwyczaj wskazuje na zanieczyszczenie lub poważne błędy w przechowywaniu.',
        'nl': 'Scherpe, industriële aromatische noot. Wijst meestal op besmetting of grote opslagfouten.',
        'sv': 'Skarp, industriell aromatisk not. Tyder vanligtvis på kontaminering eller stora lagringsfel.',
        'tr': 'Keskin, endüstriyel aromatik nota. Genellikle kirlenmeyi veya büyük depolama hatalarını gösterir.',
        'ja': 'ツンとする、工業的なアロマ。通常、汚染や重大な保管上の欠陥を示しています。',
        'ko': '자극적인 산업용 아로마 노트입니다. 보통 오염이나 중대한 저장 결함을 나타냅니다.',
        'zh': '尖锐的工业化学风味。通常预示着污染或严重的储存缺陷。',
        'ar': 'نوتة عطرية صناعية حادة. تشير عادة إلى التلوث أو عيوب كبيرة في التخزين.',
    },
    'wheel_note_medicinal': {
        'en': 'Iodine or phenol-like scent. Often result of water-borne pathogens during processing. Indicator of poor quality control.',
        'de': 'Jod- oder phenolähnlicher Geruch. Oft das Ergebnis von wasserbürtigen Pathogenen während der Verarbeitung.',
        'fr': 'Odeur d\'iode ou de phénol. Souvent le résultat de pathogènes d\'origine hydrique pendant le traitement.',
        'es': 'Olor a yodo o fenol. A menudo resultado de patógenos transmitidos por el agua durante el procesamiento.',
        'it': 'Odore di iodio o fenolo. Spesso risultato di agenti patogeni trasmessi dall\'acqua durante la lavorazione.',
        'pt': 'Cheiro de iodo ou fenol. Frequentemente resultado de patógenos transmitidos pela água durante o processamento.',
        'pl': 'Zapach jodu lub fenolu. Często wynik patogenów przenoszonych przez wodę podczas przetwarzania.',
        'nl': 'Jodium- of fenolachtige geur. Vaak het resultaat van via water overgedragen pathogenen tijdens de verwerking.',
        'sv': 'Doft av jod eller fenol. Ofta ett resultat av vattenburna patogener under bearbetningen.',
        'tr': 'İyot veya fenol benzeri koku. Genellikle işleme sırasında suyla taşınan patojenlerin sonucudur.',
        'ja': 'ヨウ素やフェノールのような香り。多くの場合、精製中の水由来の病原菌の結果です。',
        'ko': '요오드나 페놀 같은 향입니다. 가공 과정 중 수인성 병원균으로 인해 발생하는 경우가 많습니다.',
        'zh': '碘或苯酚般的味道。通常是处理过程中水载病原体的结果。',
        'ar': 'رائحة تشبه اليود أو الفينول. ناتجة غالباً عن مسببات الأمراض المنقولة بالماء أثناء المعالجة.',
    },
    'wheel_note_stale': {
        'en': 'Flat, dull profile lacking aromatics. Direct indicator of oxidation and lack of freshness. Common in old warehouse stocks.',
        'de': 'Flaches, stumpfes Profil ohne Aromen. Direkter Indikator für Oxidation und mangelnde Frische.',
        'fr': 'Profil plat et terne manquant d\'aromatiques. Indicateur direct d\'oxydation et de manque de fraîcheur.',
        'es': 'Perfil plano y apagado que carece de aromas. Indicador directo de oxidación y falta de frescura.',
        'it': 'Profilo piatto e spento privo di aromi. Indicatore diretto di ossidazione e mancanza di freschezza.',
        'pt': 'Perfil plano e opaco sem aromáticos. Indicador direto de oxidação e falta de frescor.',
        'pl': 'Płaski, matowy profil pozbawiony aromatów. Bezpośredni wskaźnik utlenienia i braku świeżości.',
        'nl': 'Vlak, dof profiel zonder aromaten. Directe indicatie van oxidatie en gebrek aan versheid.',
        'sv': 'Platt, matt profil som saknar aromer. Direkt indikator på oxidering och brist på färskhet.',
        'tr': 'Aromatikten yoksun, düz, donuk profil. Oksidasyonun ve tazelik eksikliğinin doğrudan göstergesidir.',
        'ja': 'アロマに欠ける、平坦で退屈なプロファイル。酸化と鮮度の欠如を直接示しています。',
        'ko': '아로마가 부족하고 밋밋하며 둔탁한 프로파일입니다. 산화와 신선도 부족을 직접적으로 나타냅니다.',
        'zh': '平淡、沉闷且缺乏香气的特征。是氧化和不新鲜的直接指标。',
        'ar': 'ملف نكهة مسطح وباهت يفتقر إلى الروائح العطرية. مؤشر مباشر على الأكسدة ونقص الطزاجة.',
    },
    'wheel_note_musty': {
        'en': 'Damp and earthy fault associated with moisture damage. Result of fungal growth during drying. Defect associated with poor processing.',
        'de': 'Feuchter und erdiger Fehler im Zusammenhang mit Feuchtigkeitsschäden. Ergebnis von Pilzwachstum während der Trocknung.',
        'fr': 'Défaut humide et terreux associé aux dommages causés par l\'humidité. Résultat d\'une croissance fongique pendant le séchage.',
        'es': 'Falla húmeda y terrosa asociada con daños por humedad. Resultado del crecimiento de hongos durante el secado.',
        'it': 'Difetto umido e terroso associato a danni da umidità. Risultato della crescita fungina durante l\'essiccazione.',
        'pt': 'Defeito úmido e terroso associado a danos por umidade. Resultado do crescimento de fungos durante a secagem.',
        'pl': 'Wilgotna i ziemista wada związana z uszkodzeniem przez wilgoć. Wynik wzrostu grzybów podczas suszenia.',
        'nl': 'Vochtige en aardse fout geassocieerd met vochtschade. Resultaat van schimmelgroei tijdens het drogen.',
        'sv': 'Fuktigt och jordigt fel förknippat med fuktskador. Resultat av mögeltillväxt under torkningen.',
        'tr': 'Nem hasarıyla ilişkili nemli ve topraksı kusur. Kurutma sırasında mantar büyümesinin sonucudur.',
        'ja': '湿気によるダメージに関連する、湿った土のような欠陥。乾燥中のカビの繁殖の結果です.',
        'ko': '습기 피해와 관련된 눅눅하고 흙 같은 결함입니다. 건조 과정 중 곰팡이 번식의 결과입니다.',
        'zh': '与受潮有关的潮湿和泥土缺陷。是干燥过程中霉菌生长的结果。',
        'ar': 'عيب رطب وترابي يرتبط بالتلف الناتج عن الرطوبة. ناتج عن نمو الفطريات أثناء التجفيف.',
    },
    'wheel_note_dusty': {
        'en': 'Dry, mineral-like flatness. Often indicates improper cleaning of the lot or exposure to fine particulates. Found in lower-grade commercial lots.',
        'de': 'Trockene, mineralartige Flachheit. Weist oft auf unsachgemäße Reinigung der Partie oder Belastung durch feine Partikel hin.',
        'fr': 'Platitude sèche, de type minéral. Indique souvent un nettoyage inapproprié du lot ou une exposition à de fines particules.',
        'es': 'Plantez seca, de tipo mineral. A menudo indica una limpieza inadecuada del lote o exposición a partículas finas.',
        'it': 'Piattezza secca, di tipo minerale. Spesso indica una pulizia impropria del lotto o l\'esposizione a particolato fine.',
        'pt': 'Planicidade seca, tipo mineral. Frequentemente indica limpeza inadequada do lote ou exposição a partículas finas.',
        'pl': 'Sucha, mineralna płaskość. Często wskazuje na niewłaściwe czyszczenie partii lub narażenie na drobne cząstki.',
        'nl': 'Droge, mineraalachtige vlakheid. Wijst vaak op onjuiste reiniging van de kavel of blootstelling aan fijne deeltjes.',
        'sv': 'Torr, mineralliknande platthet. Tyder ofta på felaktig rengöring av partiet eller exponering för fina partiklar.',
        'tr': 'Kuru, mineral benzeri düzlük. Genellikle lotun uygunsuz temizlendiğini veya ince partiküllere maruz kaldığını gösterir.',
        'ja': '乾燥した、ミネラルのような平坦さ。ロットの洗浄不備や微粒子の付着を示していることが多いです。',
        'ko': '건조하고 미네랄 같은 밋밋함입니다. 종종 로트의 부적절한 세척이나 미세 입자 노출을 나타냅니다.',
        'zh': '干燥、像矿物质般的平淡感。通常预示着批次清洁不当或暴露在细微颗粒中。',
        'ar': 'نكهة مسطحة جافة تشبه المعادن. غالباً ما تشير إلى تنظيف غير لائق للمحصول أو التعرض لجزيئات دقيقة.',
    },
}

update_file(r'd:\Games\Coffeeapp\lib\core\l10n\flavor_descriptions.dart', final_notes)
