import re

path = r'd:\Games\Coffeeapp\lib\core\l10n\app_localizations.dart'

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

core_ui_keys = {
    'it': {
        'variety': 'Varietà',
        'region': 'Regione',
        'farm': 'Fattoria',
        'station': 'Stazione',
        'farmer': 'Produttore',
        'altitude': 'Altitudine',
        'decaf': 'Decaffeinato',
        'ground': 'Macinato',
        'sca_score': 'Punteggio SCA',
        'roastery': 'Torrefazione',
        'roast_country': 'Paese di Tostatura',
        'roast_level_label': 'Livello di Tostatura',
        'roast_date_label': 'Data di Tostatura',
        'opened_at_label': 'Aperto il',
        'weight': 'Peso',
        'yes': 'Sì',
        'no': 'No',
        'roast_and_purchase': 'Tostatura e Acquisto',
        'coffee_process_section': 'Caffè e Processo',
        'origin_farm_section': 'Origine e Fattoria',
    },
    'pt': {
        'variety': 'Variedade',
        'region': 'Região',
        'farm': 'Fazenda',
        'station': 'Estação',
        'farmer': 'Produtor',
        'altitude': 'Altitude',
        'decaf': 'Descafeinado',
        'ground': 'Moído',
        'sca_score': 'Pontuação SCA',
        'roastery': 'Torrefação',
        'roast_country': 'País de Torra',
        'roast_level_label': 'Nível de Torra',
        'roast_date_label': 'Data de Torra',
        'opened_at_label': 'Aberto em',
        'weight': 'Peso',
        'yes': 'Sim',
        'no': 'Não',
        'roast_and_purchase': 'Torra e Compra',
        'coffee_process_section': 'Café e Processo',
        'origin_farm_section': 'Origem e Fazenda',
    },
    'pl': {
        'variety': 'Odmiana',
        'region': 'Region',
        'farm': 'Farma',
        'station': 'Stacja',
        'farmer': 'Farmer',
        'altitude': 'Wysokość',
        'decaf': 'Bezkofeinowa',
        'ground': 'Mielona',
        'sca_score': 'Wynik SCA',
        'roastery': 'Palarnia',
        'roast_country': 'Kraj Palenia',
        'roast_level_label': 'Stopień Palenia',
        'roast_date_label': 'Data Palenia',
        'opened_at_label': 'Otwarto dnia',
        'weight': 'Waga',
        'yes': 'Tak',
        'no': 'Nie',
        'roast_and_purchase': 'Palenie i Zakup',
        'coffee_process_section': 'Kawa i Obróbka',
        'origin_farm_section': 'Pochodzenie i Farma',
    },
    'nl': {
        'variety': 'Variëteit',
        'region': 'Regio',
        'farm': 'Boerderij',
        'station': 'Station',
        'farmer': 'Boer',
        'altitude': 'Hoogte',
        'decaf': 'Decaf',
        'ground': 'Gemalen',
        'sca_score': 'SCA Score',
        'roastery': 'Branderij',
        'roast_country': 'Land van branding',
        'roast_level_label': 'Brandgraad',
        'roast_date_label': 'Branddatum',
        'opened_at_label': 'Geopend op',
        'weight': 'Gewicht',
        'yes': 'Ja',
        'no': 'Nee',
        'roast_and_purchase': 'Branding & Aankoop',
        'coffee_process_section': 'Koffie & Proces',
        'origin_farm_section': 'Herkomst & Boerderij',
    },
    'sv': {
        'variety': 'Varietet',
        'region': 'Region',
        'farm': 'Gård',
        'station': 'Station',
        'farmer': 'Odlare',
        'altitude': 'Höjd',
        'decaf': 'Koffeinfritt',
        'ground': 'Malet',
        'sca_score': 'SCA-poäng',
        'roastery': 'Rosteri',
        'roast_country': 'Rostningsland',
        'roast_level_label': 'Rostningsgrad',
        'roast_date_label': 'Rostningsdatum',
        'opened_at_label': 'Öppnad den',
        'weight': 'Vikt',
        'yes': 'Ja',
        'no': 'Nej',
        'roast_and_purchase': 'Rostning & Inköp',
        'coffee_process_section': 'Kaffe & Process',
        'origin_farm_section': 'Ursprung & Gård',
    },
    'tr': {
        'variety': 'Varyete',
        'region': 'Bölge',
        'farm': 'Çiftlik',
        'station': 'İstasyon',
        'farmer': 'Çiftçi',
        'altitude': 'Rakım',
        'decaf': 'Kafeinsiz',
        'ground': 'Öğütülmüş',
        'sca_score': 'SCA Puanı',
        'roastery': 'Kavurucu',
        'roast_country': 'Kavurma Ülkesi',
        'roast_level_label': 'Kavurma Derecesi',
        'roast_date_label': 'Kavurma Tarihi',
        'opened_at_label': 'Açılış Tarihi',
        'weight': 'Ağırlık',
        'yes': 'Evet',
        'no': 'Hayır',
        'roast_and_purchase': 'Kavurma ve Satın Alma',
        'coffee_process_section': 'Kahve ve İşleme',
        'origin_farm_section': 'Köken ve Çiftlik',
    },
    'ja': {
        'variety': '品種',
        'region': '地域',
        'farm': '農園',
        'station': '精製所',
        'farmer': '生産者',
        'altitude': '標高',
        'decaf': 'デカフェ',
        'ground': '粉',
        'sca_score': 'SCAスコア',
        'roastery': 'ロースタリー',
        'roast_country': '焙煎国',
        'roast_level_label': '焙煎度',
        'roast_date_label': '焙煎日',
        'opened_at_label': '開封日',
        'weight': '内容量',
        'yes': 'はい',
        'no': 'いいえ',
        'roast_and_purchase': '焙煎・購入',
        'coffee_process_section': 'コーヒー・精製',
        'origin_farm_section': '産地・農園',
    },
    'ko': {
        'variety': '품종',
        'region': '지역',
        'farm': '농장',
        'station': '가공소',
        'farmer': '생산자',
        'altitude': '고도',
        'decaf': '디카페인',
        'ground': '분쇄두',
        'sca_score': 'SCA 점수',
        'roastery': '로스터리',
        'roast_country': '로스팅 국가',
        'roast_level_label': '로스팅 단계',
        'roast_date_label': '로스팅 날짜',
        'opened_at_label': '개봉일',
        'weight': '중량',
        'yes': '예',
        'no': '아니오',
        'roast_and_purchase': '로스팅 및 구매',
        'coffee_process_section': '커피 및 가공',
        'origin_farm_section': '원산지 및 농장',
    },
    'zh': {
        'variety': '品种',
        'region': '产区',
        'farm': '庄园',
        'station': '处理站',
        'farmer': '农户',
        'altitude': '海拔',
        'decaf': '低因',
        'ground': '咖啡粉',
        'sca_score': 'SCA评分',
        'roastery': '烘焙商',
        'roast_country': '烘焙国家',
        'roast_level_label': '烘焙程度',
        'roast_date_label': '烘焙日期',
        'opened_at_label': '开启日期',
        'weight': '重量',
        'yes': '是',
        'no': '否',
        'roast_and_purchase': '烘焙与购买',
        'coffee_process_section': '咖啡与处理',
        'origin_farm_section': '产地与庄园',
    },
    'ar': {
        'variety': 'السلالة',
        'region': 'المنطقة',
        'farm': 'المزرعة',
        'station': 'محطة المعالجة',
        'farmer': 'المزارع',
        'altitude': 'الارتفاع',
        'decaf': 'خالية من الكافيين',
        'ground': 'مطحونة',
        'sca_score': 'تقييم SCA',
        'roastery': 'المحمصة',
        'roast_country': 'بلد التحميص',
        'roast_level_label': 'درجة التحميص',
        'roast_date_label': 'تاريخ التحميص',
        'opened_at_label': 'تاريخ الفتح',
        'weight': 'الوزن',
        'yes': 'نعم',
        'no': 'لا',
        'roast_and_purchase': 'التحميص والشراء',
        'coffee_process_section': 'القهوة والمعالجة',
        'origin_farm_section': 'المنشأ والمزرعة',
    }
}

def update_langs(match):
    existing_content = match.group(1)
    for lang, keys in core_ui_keys.items():
        lang_pattern = f"'{lang}':\\s*\\{{(.*?)\n    \\}},"
        lang_match = re.search(lang_pattern, existing_content, re.DOTALL)
        if lang_match:
            block = lang_match.group(1)
            new_entries = []
            for k, v in keys.items():
                if f"'{k}':" not in block:
                    new_entries.append(f"      '{k}': '{v}',")
            if new_entries:
                new_block = block.rstrip() + "\n" + "\n".join(new_entries)
                existing_content = existing_content.replace(block, new_block)
    
    return "  static const Map<String, Map<String, String>> _translations = {" + existing_content + "  };"

new_content = re.sub(r'static const Map<String, Map<String, String>> _translations = \{(.*?)\};', update_langs, content, flags=re.DOTALL)

with open(path, 'w', encoding='utf-8') as f:
    f.write(new_content)

print("Added core coffee UI keys to 10 languages in app_localizations.dart.")
